package br.com.fiap.chat.utils;

public enum Commands {
	NOTIFICATION,
	ACCESS,
	REQUEST_USER_NAME,
	SEND_USER_NAME,
	MENU_APP,
	MENU_ROOM,
	INVALID_COMMAND,
	REQUEST_CREATE_ROOM,
	SEND_CREATE_ROOM,
	REQUEST_JOIN_ROOM,
	SEND_JOIN_ROOM,
	REQUEST_MESSAGE,
	SEND_MESSAGE,
	REQUEST_MESSAGE_PRIVATE,
	SEND_MESSAGE_PRIVATE,
	REQUEST_PRIVATE_USER,
	SEND_PRIVATE_USER;
}
